# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-18 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210718_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
